# HASIL GENERATE dari packages/contracts (bun run gen:contracts). JANGAN DIEDIT MANUAL.
# generated by datamodel-codegen:
#   filename:  bundle.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel


class SmipContracts(RootModel[Any]):
    root: Annotated[Any, Field(title='SmipContracts')]


class ContentType(StrEnum):
    post = 'post'
    reply = 'reply'
    repost = 'repost'
    quote = 'quote'
    comment = 'comment'


class Author(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform_user_id: Annotated[str, Field(min_length=1)]
    handle: str | None


class Parent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform_post_id: Annotated[str, Field(min_length=1)]
    author: Author | None


class Followers(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Following(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class CreatedAt(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]


class Author1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform_user_id: Annotated[str, Field(min_length=1)]
    handle: Annotated[str, Field(min_length=1)]
    display_name: str | None
    followers: Followers | None
    following: Following | None
    verified: bool | None
    created_at: CreatedAt | None
    location_raw: str | None
    avatar_url: AnyUrl | None


class Likes(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Comments(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Shares(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Views(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Quotes(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Saves(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Metrics(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    likes: Likes | None
    comments: Comments | None
    shares: Shares | None
    views: Views | None
    quotes: Quotes | None
    saves: Saves | None
    captured_at: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]


class Type(StrEnum):
    image = 'image'
    video = 'video'
    gif = 'gif'


class MediaItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Type
    url: AnyUrl
    thumb: AnyUrl | None = None


class Lat(RootModel[float]):
    root: Annotated[float, Field(ge=-90.0, le=90.0)]


class Lng(RootModel[float]):
    root: Annotated[float, Field(ge=-180.0, le=180.0)]


class Geo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    lat: Lat | None
    lng: Lng | None
    place_name: str | None


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector_key: Annotated[str, Field(min_length=1)]
    connector_version: Annotated[str, Field(min_length=1)]
    fetched_at: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    raw_ref: str | None


class CanonicalItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_: Annotated[Literal['canonical-item/v1'], Field(alias='schema')]
    platform: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,31}$')]
    platform_post_id: Annotated[str, Field(min_length=1)]
    content_type: ContentType
    url: AnyUrl | None
    text: str
    lang_hint: str | None
    published_at: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    parent: Parent | None
    root_post_id: str | None
    author: Author1
    metrics: Metrics
    hashtags: list[str]
    mentions: list[str]
    media: list[MediaItem]
    geo: Geo
    is_ad: bool | None
    extra: dict[str, Any]
    provenance: Provenance


class PostId(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class EngagementRefreshPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    crawl_run_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    scheduled_for: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    platform: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,31}$')]
    post_ids: Annotated[list[PostId], Field(max_length=50, min_length=1)]
    reason: Annotated[str, Field(max_length=100)]


class TenantId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class Trace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    traceparent: Annotated[
        str | None, Field(pattern='^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$')
    ] = None


class Envelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    type: Annotated[str, Field(pattern='^[a-z]+(\\.[a-z_]+)+$')]
    id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    idempotency_key: Annotated[str, Field(pattern='^[A-Za-z0-9._-]{1,200}$')]
    tenant_id: TenantId | None
    created_at: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    trace: Trace
    payload: Any


class Operation(StrEnum):
    search_keyword = 'search_keyword'
    search_hashtag = 'search_hashtag'
    user_timeline = 'user_timeline'
    post_comments = 'post_comments'
    post_detail = 'post_detail'
    profile = 'profile'
    health_probe = 'health_probe'


class Query(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    native: str
    sourceNodeIds: list[str]


class Window(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    since: Annotated[
        str | None,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ] = None
    until: Annotated[
        str | None,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ] = None


class Request(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requestId: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    idempotencyKey: Annotated[str, Field(pattern='^[A-Za-z0-9._-]{1,200}$')]
    platform: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,31}$')]
    operation: Operation
    queries: Annotated[list[Query] | None, Field(max_length=50)] = None
    targetIds: list[str] | None = None
    window: Window | None = None
    cursor: str | None = None
    pageLimit: Annotated[int, Field(ge=1, le=9007199254740991)]
    maxItems: Annotated[int, Field(ge=1, le=9007199254740991)]


class AsyncHandle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: str
    id: str
    startedAt: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    pollAfterMs: Annotated[int, Field(ge=0, le=9007199254740991)]


class Resume(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    async_handle: AsyncHandle
    query_index: Annotated[int, Field(ge=0, le=9007199254740991)]
    page: Annotated[int, Field(ge=1, le=9007199254740991)]
    seq: Annotated[int, Field(ge=1, le=9007199254740991)]


class FetchRequestPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    crawl_run_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    attempt_no: Annotated[int, Field(ge=1, le=9007199254740991)]
    connector_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    connector_key: Annotated[str, Field(min_length=1)]
    connector_version: Annotated[str, Field(min_length=1)]
    provider_account_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    reservation_id: Annotated[str, Field(min_length=1)]
    request: Request
    deadline_at: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]
    resume: Resume | None = None


class Outcome(StrEnum):
    success = 'success'
    error = 'error'


class Code(StrEnum):
    RATE_LIMITED = 'RATE_LIMITED'
    QUOTA_EXHAUSTED = 'QUOTA_EXHAUSTED'
    AUTH_INVALID = 'AUTH_INVALID'
    CHALLENGE_REQUIRED = 'CHALLENGE_REQUIRED'
    FORBIDDEN = 'FORBIDDEN'
    BLOCKED = 'BLOCKED'
    NOT_SUPPORTED = 'NOT_SUPPORTED'
    INVALID_QUERY = 'INVALID_QUERY'
    UPSTREAM_5XX = 'UPSTREAM_5XX'
    TIMEOUT = 'TIMEOUT'
    NETWORK = 'NETWORK'
    PARSE_ERROR = 'PARSE_ERROR'
    ASYNC_PENDING = 'ASYNC_PENDING'
    UNKNOWN = 'UNKNOWN'


class RetryAfterMs(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class Scope(StrEnum):
    request = 'request'
    account = 'account'
    connector = 'connector'


class HttpStatus(RootModel[int]):
    root: Annotated[int, Field(ge=-9007199254740991, le=9007199254740991)]


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Code
    message: str
    retry_after_ms: RetryAfterMs | None
    scope: Scope
    http_status: HttpStatus | None


class CostUnits(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    requests: Annotated[int, Field(ge=0, le=9007199254740991)]
    results: Annotated[int, Field(ge=0, le=9007199254740991)]
    costUnits: CostUnits | None
    costUnitLabel: str | None


class Remaining(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class ResetAt(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]


class RateLimitInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    remaining: Remaining | None
    resetAt: ResetAt | None


class ResumeState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query_index: Annotated[int, Field(ge=0, le=9007199254740991)]
    page: Annotated[int, Field(ge=1, le=9007199254740991)]


class FetchResultPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    crawl_run_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    attempt_no: Annotated[int, Field(ge=1, le=9007199254740991)]
    connector_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    provider_account_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    reservation_id: Annotated[str, Field(min_length=1)]
    outcome: Outcome
    error: Error | None
    items_ref: str | None
    items_count: Annotated[int, Field(ge=0, le=9007199254740991)]
    next_cursor: str | None
    has_more: bool
    async_handle: AsyncHandle | None
    usage: Usage
    duration_ms: Annotated[int, Field(ge=0, le=9007199254740991)]
    rate_limit_info: RateLimitInfo
    part: Annotated[int | None, Field(ge=0, le=9007199254740991)] = None
    resume_state: ResumeState | None = None


class PriorityClass(StrEnum):
    realtime = 'realtime'
    backfill = 'backfill'


class Author2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform_user_id: Annotated[str, Field(min_length=1)]
    display_name: str | None
    created_at: CreatedAt | None


class Match(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    topic_query_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,31}$')]
    post_id: Annotated[str, Field(min_length=1)]
    text: str
    lang_hint: str | None
    is_new_post: bool
    author: Author2
    match: Match


class Mode(StrEnum):
    ingest = 'ingest'
    relabel = 'relabel'


class AiEnrichPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    batch_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    crawl_run_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    tenant_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    topic_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    priority_class: PriorityClass
    items: list[Item]
    items_ref: str | None
    models: dict[str, str]
    mode: Mode | None = None


class TopicId(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]


class Sentiment(StrEnum):
    negative = 'negative'
    neutral = 'neutral'
    positive = 'positive'


class Emotion(StrEnum):
    anger = 'anger'
    anticipation = 'anticipation'
    disgust = 'disgust'
    trust = 'trust'
    joy = 'joy'
    sadness = 'sadness'
    surprise = 'surprise'
    fear = 'fear'
    unknown = 'unknown'


class AuthorGender(StrEnum):
    male = 'male'
    female = 'female'
    unknown = 'unknown'


class AuthorAgeRange(StrEnum):
    field_18_21 = '18_21'
    field_22_30 = '22_30'
    field_31_45 = '31_45'
    field_46_55 = '46_55'
    above_55 = 'above_55'
    unknown = 'unknown'


class AuthorFollowers(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=9007199254740991)]


class MediaItem1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    url: str
    thumb: str | None


class Match1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform: Annotated[str, Field(pattern='^[a-z][a-z0-9_]{0,31}$')]
    post_id: Annotated[str, Field(min_length=1)]
    topic_query_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    sentiment: Sentiment
    sentiment_score: Annotated[float, Field(ge=0.0, le=1.0)]
    emotion: Emotion
    emotion_score: Annotated[float, Field(ge=0.0, le=1.0)]
    author_gender: AuthorGender
    author_gender_conf: Annotated[float, Field(ge=0.0, le=1.0)]
    author_age_range: AuthorAgeRange
    author_age_conf: Annotated[float, Field(ge=0.0, le=1.0)]
    author_followers: AuthorFollowers | None
    model_version: Annotated[str, Field(min_length=1)]
    issues: list[str]
    hashtags: list[str]
    parent_author_id: str | None
    geo_region_code: str | None
    media: list[MediaItem1]
    engagement: Annotated[int, Field(ge=0, le=9007199254740991)]
    engagement_known: bool


class Mode1(StrEnum):
    ingest = 'ingest'
    engagement_refresh = 'engagement_refresh'
    relabel = 'relabel'


class NewHighWatermark(RootModel[str]):
    root: Annotated[
        str,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ]


class RunOutcome(StrEnum):
    succeeded = 'succeeded'
    partial = 'partial'
    failed = 'failed'


class GapWindow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    since: Annotated[
        str | None,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ] = None
    until: Annotated[
        str | None,
        Field(
            pattern='^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z))$'
        ),
    ] = None


class RunUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items_fetched: Annotated[int, Field(ge=0, le=9007199254740991)]
    items_matched: Annotated[int, Field(ge=0, le=9007199254740991)]
    items_new: Annotated[int, Field(ge=0, le=9007199254740991)]
    new_high_watermark: NewHighWatermark | None
    run_outcome: RunOutcome
    gap_window: GapWindow | None


class SinkAnalyticsPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    batch_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    crawl_run_id: Annotated[
        str,
        Field(
            pattern='^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
        ),
    ]
    tenant_id: TenantId | None
    topic_id: TopicId | None
    posts_ref: Annotated[str, Field(min_length=1)]
    matches: list[Match1]
    mode: Mode1 | None = None
    run_update: RunUpdate | None
