-- I-14: gazetteer provinsi (AI_SPEC §10). Sumber & status: docs/adr/ADR-010-gazetteer.md (kode UNVERIFIED sampai dicek reviewer).
-- Alias = bentuk ternormalisasi (huruf kecil, tanpa tanda baca): nama resmi, singkatan umum, ibu kota & kota besar.
INSERT INTO geo_regions (code, level, name, aliases) VALUES
  ('11', 'province', 'Aceh', '{aceh,nanggroe aceh darussalam,nad,banda aceh,lhokseumawe}'),
  ('12', 'province', 'Sumatera Utara', '{sumatera utara,sumatra utara,sumut,medan,binjai,pematangsiantar}'),
  ('13', 'province', 'Sumatera Barat', '{sumatera barat,sumatra barat,sumbar,padang,bukittinggi}'),
  ('14', 'province', 'Riau', '{riau,pekanbaru,dumai}'),
  ('15', 'province', 'Jambi', '{jambi}'),
  ('16', 'province', 'Sumatera Selatan', '{sumatera selatan,sumatra selatan,sumsel,palembang}'),
  ('17', 'province', 'Bengkulu', '{bengkulu}'),
  ('18', 'province', 'Lampung', '{lampung,bandar lampung}'),
  ('19', 'province', 'Kepulauan Bangka Belitung', '{kepulauan bangka belitung,bangka belitung,babel,pangkal pinang,pangkalpinang}'),
  ('21', 'province', 'Kepulauan Riau', '{kepulauan riau,kepri,batam,tanjung pinang,tanjungpinang}'),
  ('31', 'province', 'DKI Jakarta', '{dki jakarta,jakarta,dki,jkt,jakarta pusat,jakarta selatan,jakarta barat,jakarta timur,jakarta utara,jaksel,jakbar,jaktim,jakut,jakpus}'),
  ('32', 'province', 'Jawa Barat', '{jawa barat,jabar,bandung,bekasi,bogor,depok,cirebon,sukabumi,tasikmalaya,karawang}'),
  ('33', 'province', 'Jawa Tengah', '{jawa tengah,jateng,semarang,solo,surakarta,magelang,tegal,pekalongan}'),
  ('34', 'province', 'DI Yogyakarta', '{daerah istimewa yogyakarta,di yogyakarta,diy,yogyakarta,yogya,jogja,jogjakarta,sleman,bantul}'),
  ('35', 'province', 'Jawa Timur', '{jawa timur,jatim,surabaya,malang,sidoarjo,kediri,jember,madiun}'),
  ('36', 'province', 'Banten', '{banten,serang,tangerang,tangerang selatan,tangsel,cilegon}'),
  ('51', 'province', 'Bali', '{bali,denpasar,badung,gianyar}'),
  ('52', 'province', 'Nusa Tenggara Barat', '{nusa tenggara barat,ntb,mataram,lombok}'),
  ('53', 'province', 'Nusa Tenggara Timur', '{nusa tenggara timur,ntt,kupang}'),
  ('61', 'province', 'Kalimantan Barat', '{kalimantan barat,kalbar,pontianak}'),
  ('62', 'province', 'Kalimantan Tengah', '{kalimantan tengah,kalteng,palangka raya,palangkaraya}'),
  ('63', 'province', 'Kalimantan Selatan', '{kalimantan selatan,kalsel,banjarmasin,banjarbaru}'),
  ('64', 'province', 'Kalimantan Timur', '{kalimantan timur,kaltim,samarinda,balikpapan}'),
  ('65', 'province', 'Kalimantan Utara', '{kalimantan utara,kaltara,tanjung selor,tarakan}'),
  ('71', 'province', 'Sulawesi Utara', '{sulawesi utara,sulut,manado}'),
  ('72', 'province', 'Sulawesi Tengah', '{sulawesi tengah,sulteng,palu}'),
  ('73', 'province', 'Sulawesi Selatan', '{sulawesi selatan,sulsel,makassar}'),
  ('74', 'province', 'Sulawesi Tenggara', '{sulawesi tenggara,sultra,kendari}'),
  ('75', 'province', 'Gorontalo', '{gorontalo}'),
  ('76', 'province', 'Sulawesi Barat', '{sulawesi barat,sulbar,mamuju}'),
  ('81', 'province', 'Maluku', '{maluku,ambon}'),
  ('82', 'province', 'Maluku Utara', '{maluku utara,malut,ternate,sofifi}'),
  ('91', 'province', 'Papua', '{papua,jayapura}'),
  ('92', 'province', 'Papua Barat', '{papua barat,manokwari}'),
  ('93', 'province', 'Papua Selatan', '{papua selatan,merauke}'),
  ('94', 'province', 'Papua Tengah', '{papua tengah,nabire}'),
  ('95', 'province', 'Papua Pegunungan', '{papua pegunungan,wamena,jayawijaya}'),
  ('96', 'province', 'Papua Barat Daya', '{papua barat daya,sorong}')
ON CONFLICT (code) DO NOTHING;
